name: No-Std Targets

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  nostd:
    name: ARM Cortex-M
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: rustup target add thumbv7m-none-eabi
      - run: cargo check --locked --target thumbv7m-none-eabi
      - run: cargo check --locked --target thumbv7m-none-eabi --features async
